services:
  docs:
    image: gouthelper_ninja_local_docs
    container_name: gouthelper_ninja_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./gouthelper_ninja:/app/gouthelper_ninja:z
    ports:
      - '9000:9000'
    command: /start-docs
