# Generated by Django 5.1.9 on 2025-05-28 15:29

import django.db.models.deletion
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEthnicity',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('ethnicity', models.CharField(choices=[('African American', 'African American'), ('Caucasian American', 'Caucasian American'), ('East African', 'East African'), ('Han Chinese', 'Han Chinese'), ('Hispanic', 'Hispanic'), ('Hmong', 'Hmong'), ('Korean', 'Korean'), ('Native American', 'Native American'), ('Other', 'Other'), ('Pacific Islander', 'Pacific Islander'), ('Thai', 'Thai'), ('Prefer not to answer', 'Prefer not to answer')], help_text='What is the patient\'s ethnicity or race? <a href="" target="_next">Why do we need to know?</a>', max_length=40, verbose_name='Ethnicity or Race')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ethnicity',
                'verbose_name_plural': 'historical ethnicitys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ethnicity', models.CharField(choices=[('African American', 'African American'), ('Caucasian American', 'Caucasian American'), ('East African', 'East African'), ('Han Chinese', 'Han Chinese'), ('Hispanic', 'Hispanic'), ('Hmong', 'Hmong'), ('Korean', 'Korean'), ('Native American', 'Native American'), ('Other', 'Other'), ('Pacific Islander', 'Pacific Islander'), ('Thai', 'Thai'), ('Prefer not to answer', 'Prefer not to answer')], help_text='What is the patient\'s ethnicity or race? <a href="" target="_next">Why do we need to know?</a>', max_length=40, verbose_name='Ethnicity or Race')),
                ('patient', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ethnicity__in', ['African American', 'Caucasian American', 'East African', 'Han Chinese', 'Hispanic', 'Hmong', 'Korean', 'Native American', 'Other', 'Pacific Islander', 'Thai', 'Prefer not to answer'])), name='ethnicity_valid')],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
