# Generated by Django 5.1.9 on 2025-05-28 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethnicitys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ethnicity',
            name='ethnicity_valid',
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='ethnicity',
            field=models.CharField(choices=[('African American', 'African American'), ('Caucasian', 'Caucasian'), ('East African', 'East African'), ('Han Chinese', 'Han Chinese'), ('Hispanic', 'Hispanic'), ('Hmong', 'Hmong'), ('Korean', 'Korean'), ('Native American', 'Native American'), ('Other', 'Other'), ('Pacific Islander', 'Pacific Islander'), ('Thai', 'Thai'), ('Prefer not to answer', 'Prefer not to answer')], help_text='What is the patient\'s ethnicity or race? <a href="" target="_next">Why do we need to know?</a>', max_length=40, verbose_name='Ethnicity or Race'),
        ),
        migrations.AlterField(
            model_name='historicalethnicity',
            name='ethnicity',
            field=models.CharField(choices=[('African American', 'African American'), ('Caucasian', 'Caucasian'), ('East African', 'East African'), ('Han Chinese', 'Han Chinese'), ('Hispanic', 'Hispanic'), ('Hmong', 'Hmong'), ('Korean', 'Korean'), ('Native American', 'Native American'), ('Other', 'Other'), ('Pacific Islander', 'Pacific Islander'), ('Thai', 'Thai'), ('Prefer not to answer', 'Prefer not to answer')], help_text='What is the patient\'s ethnicity or race? <a href="" target="_next">Why do we need to know?</a>', max_length=40, verbose_name='Ethnicity or Race'),
        ),
        migrations.AddConstraint(
            model_name='ethnicity',
            constraint=models.CheckConstraint(condition=models.Q(('ethnicity__in', ['African American', 'Caucasian', 'East African', 'Han Chinese', 'Hispanic', 'Hmong', 'Korean', 'Native American', 'Other', 'Pacific Islander', 'Thai', 'Prefer not to answer'])), name='ethnicity_valid'),
        ),
    ]
