# Generated by Django 5.1.9 on 2025-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethnicitys', '0002_remove_ethnicity_ethnicity_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethnicity',
            name='ethnicity',
            field=models.CharField(choices=[('African American', 'African American'), ('Caucasian', 'Caucasian'), ('East African', 'East African'), ('Han Chinese', 'Han Chinese'), ('Hispanic', 'Hispanic'), ('Hmong', 'Hmong'), ('Korean', 'Korean'), ('Native American', 'Native American'), ('Other', 'Other'), ('Pacific Islander', 'Pacific Islander'), ('Thai', 'Thai'), ('Prefer not to answer', 'Prefer not to answer')], help_text="What is the patient's ethnicity or race?", max_length=40, verbose_name='Ethnicity or Race'),
        ),
        migrations.AlterField(
            model_name='historicalethnicity',
            name='ethnicity',
            field=models.CharField(choices=[('African American', 'African American'), ('Caucasian', 'Caucasian'), ('East African', 'East African'), ('Han Chinese', 'Han Chinese'), ('Hispanic', 'Hispanic'), ('Hmong', 'Hmong'), ('Korean', 'Korean'), ('Native American', 'Native American'), ('Other', 'Other'), ('Pacific Islander', 'Pacific Islander'), ('Thai', 'Thai'), ('Prefer not to answer', 'Prefer not to answer')], help_text="What is the patient's ethnicity or race?", max_length=40, verbose_name='Ethnicity or Race'),
        ),
    ]
