# Generated by Django 5.1.9 on 2025-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateofbirths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateofbirth',
            name='dateofbirth',
            field=models.DateField(help_text='How old is the patient (range: 18-120)?', verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='historicaldateofbirth',
            name='dateofbirth',
            field=models.DateField(help_text='How old is the patient (range: 18-120)?', verbose_name='Age'),
        ),
    ]
