# Generated by Django 5.1.9 on 2025-09-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateofbirths', '0002_alter_dateofbirth_dateofbirth_and_more'),
        ('users', '0004_alter_admin_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateofbirth',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='historicaldateofbirth',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.patient'),
        ),
    ]
