# Generated by Django 5.1.9 on 2025-07-27 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ults', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ult',
            name='ults_ult_freq_num_flares_valid',
        ),
        migrations.AddConstraint(
            model_name='ult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('num_flares', 2), ('freq_flares__isnull', False)), models.Q(('num_flares', 1), models.Q(('freq_flares__isnull', True), ('freq_flares', 1), _connector='OR')), models.Q(('num_flares', 0), ('freq_flares__isnull', True)), _connector='OR'), name='ults_ult_freq_num_flares_valid'),
        ),
    ]
