# Generated by Django 5.1.9 on 2025-08-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ults', '0002_remove_ult_ults_ult_freq_num_flares_valid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ult',
            name='ults_ult_indication_valid',
        ),
        migrations.RemoveField(
            model_name='historicalult',
            name='indication',
        ),
        migrations.RemoveField(
            model_name='ult',
            name='indication',
        ),
    ]
