# Generated by Django 5.1.9 on 2025-09-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ults', '0004_alter_historicalult_patient_alter_ult_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUlt',
        ),
    ]
