# Generated by Django 5.1.9 on 2025-08-02 13:17

import django.db.models.deletion
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCkdDetail',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('dialysis', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="Is the patient on <a href='https://en.wikipedia.org/wiki/Hemodialysis' target='_blank'>dialysis</a>?", verbose_name='Dialysis')),
                ('dialysis_duration', models.IntegerField(blank=True, choices=[(1, 'Less than six months'), (2, 'Between six months and a year'), (3, 'More than a year')], default=None, help_text='How long has the patient been on dialysis?', null=True, verbose_name='Time on Dialysis')),
                ('dialysis_type', models.IntegerField(blank=True, choices=[(1, 'Hemodialysis'), (2, 'Peritoneal')], default=None, help_text='What type of dialysis?', null=True, verbose_name='Dialysis Type')),
                ('stage', models.IntegerField(choices=[(None, '----'), (1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], help_text="What <a href='https://www.kidney.org/kidney-topics/stages-chronic-kidney-disease-ckd' target='_blank'>stage</a> CKD?", verbose_name='CKD Stage')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ckd detail',
                'verbose_name_plural': 'historical ckd details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CkdDetail',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dialysis', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="Is the patient on <a href='https://en.wikipedia.org/wiki/Hemodialysis' target='_blank'>dialysis</a>?", verbose_name='Dialysis')),
                ('dialysis_duration', models.IntegerField(blank=True, choices=[(1, 'Less than six months'), (2, 'Between six months and a year'), (3, 'More than a year')], default=None, help_text='How long has the patient been on dialysis?', null=True, verbose_name='Time on Dialysis')),
                ('dialysis_type', models.IntegerField(blank=True, choices=[(1, 'Hemodialysis'), (2, 'Peritoneal')], default=None, help_text='What type of dialysis?', null=True, verbose_name='Dialysis Type')),
                ('stage', models.IntegerField(choices=[(None, '----'), (1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], help_text="What <a href='https://www.kidney.org/kidney-topics/stages-chronic-kidney-disease-ckd' target='_blank'>stage</a> CKD?", verbose_name='CKD Stage')),
                ('patient', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dialysis', False), ('dialysis_duration__isnull', True), ('dialysis_type__isnull', True)), models.Q(('dialysis', True), ('dialysis_duration__isnull', False), ('dialysis_type__isnull', False), ('stage', 5)), _connector='OR'), name='ckddetail_dialysis_valid'), models.CheckConstraint(condition=models.Q(('dialysis_duration__in', [1, 2, 3])), name='ckddetail_dialysis_duration_valid'), models.CheckConstraint(condition=models.Q(('dialysis_type__in', [1, 2])), name='ckddetail_dialysis_type_valid'), models.CheckConstraint(condition=models.Q(('stage__in', [None, 1, 2, 3, 4, 5])), name='ckddetail_stage_valid')],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
