# Generated by Django 5.1.9 on 2025-08-17 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckddetails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ckddetail',
            name='ckddetail_dialysis_duration_valid',
        ),
        migrations.RemoveConstraint(
            model_name='ckddetail',
            name='ckddetail_dialysis_type_valid',
        ),
        migrations.AlterField(
            model_name='ckddetail',
            name='dialysis_duration',
            field=models.CharField(blank=True, choices=[('LESSTHANSIX', 'Less than six months'), ('LESSTHANYEAR', 'Between six months and a year'), ('MORETHANYEAR', 'More than a year')], default=None, help_text='How long has the patient been on dialysis?', max_length=12, verbose_name='Time on Dialysis'),
        ),
        migrations.AlterField(
            model_name='ckddetail',
            name='dialysis_type',
            field=models.CharField(blank=True, choices=[('HEMODIALYSIS', 'Hemodialysis'), ('PERITONEAL', 'Peritoneal Dialysis')], default=None, help_text='What type of dialysis?', max_length=12, verbose_name='Dialysis Type'),
        ),
        migrations.AlterField(
            model_name='historicalckddetail',
            name='dialysis_duration',
            field=models.CharField(blank=True, choices=[('LESSTHANSIX', 'Less than six months'), ('LESSTHANYEAR', 'Between six months and a year'), ('MORETHANYEAR', 'More than a year')], default=None, help_text='How long has the patient been on dialysis?', max_length=12, verbose_name='Time on Dialysis'),
        ),
        migrations.AlterField(
            model_name='historicalckddetail',
            name='dialysis_type',
            field=models.CharField(blank=True, choices=[('HEMODIALYSIS', 'Hemodialysis'), ('PERITONEAL', 'Peritoneal Dialysis')], default=None, help_text='What type of dialysis?', max_length=12, verbose_name='Dialysis Type'),
        ),
        migrations.AddConstraint(
            model_name='ckddetail',
            constraint=models.CheckConstraint(condition=models.Q(('dialysis_duration__in', ['LESSTHANSIX', 'LESSTHANYEAR', 'MORETHANYEAR'])), name='ckddetail_dialysis_duration_valid'),
        ),
        migrations.AddConstraint(
            model_name='ckddetail',
            constraint=models.CheckConstraint(condition=models.Q(('dialysis_type__in', ['HEMODIALYSIS', 'PERITONEAL'])), name='ckddetail_dialysis_type_valid'),
        ),
    ]
