# Generated by Django 5.1.9 on 2025-08-17 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckddetails', '0002_remove_ckddetail_ckddetail_dialysis_duration_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ckddetail',
            name='ckddetail_dialysis_duration_valid',
        ),
        migrations.RemoveConstraint(
            model_name='ckddetail',
            name='ckddetail_dialysis_type_valid',
        ),
        migrations.AlterField(
            model_name='ckddetail',
            name='dialysis_duration',
            field=models.IntegerField(blank=True, choices=[(1, 'Less than six months'), (2, 'Between six months and a year'), (3, 'More than a year')], default=None, help_text='How long has the patient been on dialysis?', null=True, verbose_name='Time on Dialysis'),
        ),
        migrations.AlterField(
            model_name='ckddetail',
            name='dialysis_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Hemodialysis'), (2, 'Peritoneal Dialysis')], default=None, help_text='What type of dialysis?', null=True, verbose_name='Dialysis Type'),
        ),
        migrations.AlterField(
            model_name='historicalckddetail',
            name='dialysis_duration',
            field=models.IntegerField(blank=True, choices=[(1, 'Less than six months'), (2, 'Between six months and a year'), (3, 'More than a year')], default=None, help_text='How long has the patient been on dialysis?', null=True, verbose_name='Time on Dialysis'),
        ),
        migrations.AlterField(
            model_name='historicalckddetail',
            name='dialysis_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Hemodialysis'), (2, 'Peritoneal Dialysis')], default=None, help_text='What type of dialysis?', null=True, verbose_name='Dialysis Type'),
        ),
        migrations.AddConstraint(
            model_name='ckddetail',
            constraint=models.CheckConstraint(condition=models.Q(('dialysis_duration__in', [1, 2, 3])), name='ckddetail_dialysis_duration_valid'),
        ),
        migrations.AddConstraint(
            model_name='ckddetail',
            constraint=models.CheckConstraint(condition=models.Q(('dialysis_type__in', [1, 2])), name='ckddetail_dialysis_type_valid'),
        ),
    ]
