# Generated by Django 5.1.9 on 2025-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], help_text="What is the patient's biological sex?", verbose_name='Biological Sex'),
        ),
        migrations.AlterField(
            model_name='historicalgender',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], help_text="What is the patient's biological sex?", verbose_name='Biological Sex'),
        ),
    ]
