# Generated by Django 5.1.9 on 2025-09-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0003_alter_gender_patient_alter_historicalgender_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalGender',
        ),
    ]
