# Generated by Django 5.1.9 on 2025-06-30 20:05

import uuid

import django.db.models.deletion
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMedHistory',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('medhistorytype', models.CharField(choices=[('ANGINA', 'Angina'), ('ANTICOAGULATION', 'Anticoagulation'), ('BLEED', 'Bleed'), ('CAD', 'Coronary Artery Disease'), ('CHF', 'Congestive Heart Failure'), ('CKD', 'Chronic Kidney Disease'), ('COLCHICINEINTERACTION', 'Colchicine Medication Interaction'), ('DIABETES', 'Diabetes'), ('EROSIONS', 'Erosions'), ('GASTRICBYPASS', 'Gastric Bypass'), ('GOUT', 'Gout'), ('HEARTATTACK', 'Heart Attack'), ('HEPATITIS', 'Hepatitis or Cirrhosis'), ('HYPERTENSION', 'Hypertension'), ('HYPERURICEMIA', 'Hyperuricemia'), ('IBD', 'Inflammatory Bowel Disease'), ('MENOPAUSE', 'Post-Menopausal'), ('ORGANTRANSPLANT', 'Organ Transplant'), ('OSTEOPOROSIS', 'Osteoporosis'), ('PUD', 'Peptic Ulcer Disease'), ('PVD', 'Peripheral Vascular Disease'), ('STROKE', 'Stroke'), ('TOPHI', 'Tophi'), ('URATESTONES', 'Urate kidney stones'), ('XOIINTERACTION', 'Xanthine Oxidase Inhibitor Medication Interaction')], editable=False, max_length=50, verbose_name='Type of medical history')),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical med history',
                'verbose_name_plural': 'historical med historys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MedHistory',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('medhistorytype', models.CharField(choices=[('ANGINA', 'Angina'), ('ANTICOAGULATION', 'Anticoagulation'), ('BLEED', 'Bleed'), ('CAD', 'Coronary Artery Disease'), ('CHF', 'Congestive Heart Failure'), ('CKD', 'Chronic Kidney Disease'), ('COLCHICINEINTERACTION', 'Colchicine Medication Interaction'), ('DIABETES', 'Diabetes'), ('EROSIONS', 'Erosions'), ('GASTRICBYPASS', 'Gastric Bypass'), ('GOUT', 'Gout'), ('HEARTATTACK', 'Heart Attack'), ('HEPATITIS', 'Hepatitis or Cirrhosis'), ('HYPERTENSION', 'Hypertension'), ('HYPERURICEMIA', 'Hyperuricemia'), ('IBD', 'Inflammatory Bowel Disease'), ('MENOPAUSE', 'Post-Menopausal'), ('ORGANTRANSPLANT', 'Organ Transplant'), ('OSTEOPOROSIS', 'Osteoporosis'), ('PUD', 'Peptic Ulcer Disease'), ('PVD', 'Peripheral Vascular Disease'), ('STROKE', 'Stroke'), ('TOPHI', 'Tophi'), ('URATESTONES', 'Urate kidney stones'), ('XOIINTERACTION', 'Xanthine Oxidase Inhibitor Medication Interaction')], editable=False, max_length=50, verbose_name='Type of medical history')),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Angina',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Anticoagulation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Bleed',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Cad',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Chf',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Ckd',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Colchicineinteraction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Erosions',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Gastricbypass',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Gout',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Heartattack',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Hepatitis',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Hypertension',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Hyperuricemia',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Ibd',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Menopause',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Organtransplant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Osteoporosis',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Pud',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Pvd',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Tophi',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Uratestones',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.CreateModel(
            name='Xoiinteraction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.AddConstraint(
            model_name='medhistory',
            constraint=models.CheckConstraint(condition=models.Q(('medhistorytype__in', ['ANGINA', 'ANTICOAGULATION', 'BLEED', 'CAD', 'CHF', 'CKD', 'COLCHICINEINTERACTION', 'DIABETES', 'EROSIONS', 'GASTRICBYPASS', 'GOUT', 'HEARTATTACK', 'HEPATITIS', 'HYPERTENSION', 'HYPERURICEMIA', 'IBD', 'MENOPAUSE', 'ORGANTRANSPLANT', 'OSTEOPOROSIS', 'PUD', 'PVD', 'STROKE', 'TOPHI', 'URATESTONES', 'XOIINTERACTION'])), name='medhistorys_medhistory_medhistorytype_valid'),
        ),
        migrations.AddConstraint(
            model_name='medhistory',
            constraint=models.UniqueConstraint(fields=('patient', 'medhistorytype'), name='medhistorys_medhistory_unique_patient'),
        ),
    ]
