# Generated by Django 5.1.9 on 2025-07-02 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhistorys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medhistory',
            name='medhistorys_medhistory_medhistorytype_valid',
        ),
        migrations.RemoveConstraint(
            model_name='medhistory',
            name='medhistorys_medhistory_unique_patient',
        ),
        migrations.RenameField(
            model_name='historicalmedhistory',
            old_name='medhistorytype',
            new_name='mhtype',
        ),
        migrations.RenameField(
            model_name='medhistory',
            old_name='medhistorytype',
            new_name='mhtype',
        ),
        migrations.AddConstraint(
            model_name='medhistory',
            constraint=models.CheckConstraint(condition=models.Q(('mhtype__in', ['ANGINA', 'ANTICOAGULATION', 'BLEED', 'CAD', 'CHF', 'CKD', 'COLCHICINEINTERACTION', 'DIABETES', 'EROSIONS', 'GASTRICBYPASS', 'GOUT', 'HEARTATTACK', 'HEPATITIS', 'HYPERTENSION', 'HYPERURICEMIA', 'IBD', 'MENOPAUSE', 'ORGANTRANSPLANT', 'OSTEOPOROSIS', 'PUD', 'PVD', 'STROKE', 'TOPHI', 'URATESTONES', 'XOIINTERACTION'])), name='medhistorys_medhistory_mhtype_valid'),
        ),
        migrations.AddConstraint(
            model_name='medhistory',
            constraint=models.UniqueConstraint(fields=('patient', 'mhtype'), name='medhistorys_medhistory_unique_patient'),
        ),
    ]
