# Generated by Django 5.1.9 on 2025-07-03 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhistorys', '0002_remove_medhistory_medhistorys_medhistory_medhistorytype_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pvd',
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medhistorys.medhistory',),
        ),
        migrations.RemoveConstraint(
            model_name='medhistory',
            name='medhistorys_medhistory_mhtype_valid',
        ),
        migrations.AlterField(
            model_name='historicalmedhistory',
            name='mhtype',
            field=models.CharField(choices=[('ANGINA', 'Angina'), ('ANTICOAGULATION', 'Anticoagulation'), ('BLEED', 'Bleed'), ('CAD', 'Coronary Artery Disease'), ('CHF', 'Congestive Heart Failure'), ('CKD', 'Chronic Kidney Disease'), ('COLCHICINEINTERACTION', 'Colchicine Medication Interaction'), ('DIABETES', 'Diabetes'), ('EROSIONS', 'Erosions'), ('GASTRICBYPASS', 'Gastric Bypass'), ('GOUT', 'Gout'), ('HEARTATTACK', 'Heart Attack'), ('HEPATITIS', 'Hepatitis or Cirrhosis'), ('HYPERTENSION', 'Hypertension'), ('HYPERURICEMIA', 'Hyperuricemia'), ('IBD', 'Inflammatory Bowel Disease'), ('MENOPAUSE', 'Post-Menopausal'), ('ORGANTRANSPLANT', 'Organ Transplant'), ('OSTEOPOROSIS', 'Osteoporosis'), ('PUD', 'Peptic Ulcer Disease'), ('PAD', 'Peripheral Vascular Disease'), ('STROKE', 'Stroke'), ('TOPHI', 'Tophi'), ('URATESTONES', 'Urate kidney stones'), ('XOIINTERACTION', 'Xanthine Oxidase Inhibitor Medication Interaction')], editable=False, max_length=50, verbose_name='Type of medical history'),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='mhtype',
            field=models.CharField(choices=[('ANGINA', 'Angina'), ('ANTICOAGULATION', 'Anticoagulation'), ('BLEED', 'Bleed'), ('CAD', 'Coronary Artery Disease'), ('CHF', 'Congestive Heart Failure'), ('CKD', 'Chronic Kidney Disease'), ('COLCHICINEINTERACTION', 'Colchicine Medication Interaction'), ('DIABETES', 'Diabetes'), ('EROSIONS', 'Erosions'), ('GASTRICBYPASS', 'Gastric Bypass'), ('GOUT', 'Gout'), ('HEARTATTACK', 'Heart Attack'), ('HEPATITIS', 'Hepatitis or Cirrhosis'), ('HYPERTENSION', 'Hypertension'), ('HYPERURICEMIA', 'Hyperuricemia'), ('IBD', 'Inflammatory Bowel Disease'), ('MENOPAUSE', 'Post-Menopausal'), ('ORGANTRANSPLANT', 'Organ Transplant'), ('OSTEOPOROSIS', 'Osteoporosis'), ('PUD', 'Peptic Ulcer Disease'), ('PAD', 'Peripheral Vascular Disease'), ('STROKE', 'Stroke'), ('TOPHI', 'Tophi'), ('URATESTONES', 'Urate kidney stones'), ('XOIINTERACTION', 'Xanthine Oxidase Inhibitor Medication Interaction')], editable=False, max_length=50, verbose_name='Type of medical history'),
        ),
        migrations.AddConstraint(
            model_name='medhistory',
            constraint=models.CheckConstraint(condition=models.Q(('mhtype__in', ['ANGINA', 'ANTICOAGULATION', 'BLEED', 'CAD', 'CHF', 'CKD', 'COLCHICINEINTERACTION', 'DIABETES', 'EROSIONS', 'GASTRICBYPASS', 'GOUT', 'HEARTATTACK', 'HEPATITIS', 'HYPERTENSION', 'HYPERURICEMIA', 'IBD', 'MENOPAUSE', 'ORGANTRANSPLANT', 'OSTEOPOROSIS', 'PUD', 'PAD', 'STROKE', 'TOPHI', 'URATESTONES', 'XOIINTERACTION'])), name='medhistorys_medhistory_mhtype_valid'),
        ),
    ]
