# Generated by Django 5.1.9 on 2025-09-06 15:32

import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhistorys', '0005_remove_historicalanticoagulation_history_user_and_more'),
        ('users', '0004_alter_admin_options_alter_patient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMedHistory',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('mhtype', models.CharField(choices=[('ANGINA', 'Angina'), ('ANTICOAGULATION', 'Anticoagulation'), ('BLEED', 'Bleed'), ('CAD', 'Coronary Artery Disease'), ('CHF', 'Congestive Heart Failure'), ('CKD', 'Chronic Kidney Disease'), ('COLCHICINEINTERACTION', 'Colchicine Medication Interaction'), ('DIABETES', 'Diabetes'), ('EROSIONS', 'Erosions'), ('GASTRICBYPASS', 'Gastric Bypass'), ('GOUT', 'Gout'), ('HEARTATTACK', 'Heart Attack'), ('HEPATITIS', 'Hepatitis or Cirrhosis'), ('HYPERTENSION', 'Hypertension'), ('HYPERURICEMIA', 'Hyperuricemia'), ('IBD', 'Inflammatory Bowel Disease'), ('MENOPAUSE', 'Post-Menopausal'), ('ORGANTRANSPLANT', 'Organ Transplant'), ('OSTEOPOROSIS', 'Osteoporosis'), ('PUD', 'Peptic Ulcer Disease'), ('PAD', 'Peripheral Vascular Disease'), ('STROKE', 'Stroke'), ('TOPHI', 'Tophi'), ('URATESTONES', 'Urate kidney stones'), ('XOIINTERACTION', 'Xanthine Oxidase Inhibitor Medication Interaction')], editable=False, max_length=50, verbose_name='Type of medical history')),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.patient')),
            ],
            options={
                'verbose_name': 'historical med history',
                'verbose_name_plural': 'historical med historys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
