# Generated by Django 5.1.9 on 2025-10-04 13:28

import django.db.models.deletion
import django_extensions.db.fields
import gouthelper_ninja.utils.model_mixins
import rules.contrib.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhistorys', '0006_historicalmedhistory'),
        ('users', '0005_historicaladmin_historicalpatient_historicalprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Angina',
        ),
        migrations.DeleteModel(
            name='Anticoagulation',
        ),
        migrations.DeleteModel(
            name='Bleed',
        ),
        migrations.DeleteModel(
            name='Cad',
        ),
        migrations.DeleteModel(
            name='Chf',
        ),
        migrations.DeleteModel(
            name='Ckd',
        ),
        migrations.DeleteModel(
            name='Colchicineinteraction',
        ),
        migrations.DeleteModel(
            name='Diabetes',
        ),
        migrations.DeleteModel(
            name='Erosions',
        ),
        migrations.DeleteModel(
            name='Gastricbypass',
        ),
        migrations.DeleteModel(
            name='Gout',
        ),
        migrations.DeleteModel(
            name='Heartattack',
        ),
        migrations.DeleteModel(
            name='Hepatitis',
        ),
        migrations.DeleteModel(
            name='Hypertension',
        ),
        migrations.DeleteModel(
            name='Hyperuricemia',
        ),
        migrations.DeleteModel(
            name='Ibd',
        ),
        migrations.DeleteModel(
            name='Menopause',
        ),
        migrations.DeleteModel(
            name='Organtransplant',
        ),
        migrations.DeleteModel(
            name='Osteoporosis',
        ),
        migrations.DeleteModel(
            name='Pad',
        ),
        migrations.DeleteModel(
            name='Pud',
        ),
        migrations.DeleteModel(
            name='Stroke',
        ),
        migrations.DeleteModel(
            name='Tophi',
        ),
        migrations.DeleteModel(
            name='Uratestones',
        ),
        migrations.DeleteModel(
            name='Xoiinteraction',
        ),
        migrations.RemoveField(
            model_name='medhistory',
            name='patient',
        ),
        migrations.CreateModel(
            name='Angina',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Anticoagulation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Bleed',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Cad',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Chf',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Ckd',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Colchicineinteraction',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Erosions',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Gastricbypass',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Gout',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Heartattack',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Hepatitis',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Hypertension',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Hyperuricemia',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Ibd',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Menopause',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organtransplant',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Osteoporosis',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Pud',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tophi',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Uratestones',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Xoiinteraction',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('history_of', models.BooleanField(default=False, help_text='Does the patient have this medical history?', verbose_name='History of')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=(gouthelper_ninja.utils.model_mixins.GoutHelperCrudMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalMedHistory',
        ),
        migrations.DeleteModel(
            name='MedHistory',
        ),
    ]
