# Generated by Django 5.1.9 on 2025-10-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhistorys', '0008_historicalangina_historicalanticoagulation_and_more'),
        ('users', '0005_historicaladmin_historicalpatient_historicalprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angina',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='anticoagulation',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='bleed',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='cad',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='chf',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='ckd',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='colchicineinteraction',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='erosions',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='gastricbypass',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='gout',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='hepatitis',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='hypertension',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='hyperuricemia',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='ibd',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='menopause',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='organtransplant',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='osteoporosis',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='pad',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='pud',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='tophi',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='uratestones',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='xoiinteraction',
            name='patient',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
    ]
