# Generated by Django 5.1.9 on 2025-08-18 11:35

import django.db.models.deletion
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBaselineCreatinine',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('lower_limit', models.DecimalField(decimal_places=2, default=Decimal('0.74'), max_digits=4)),
                ('units', models.CharField(choices=[('MGDL', 'mg/dL (milligrams per deciliter)')], default='MGDL', max_length=10, verbose_name='Units')),
                ('upper_limit', models.DecimalField(decimal_places=2, default=Decimal('1.35'), max_digits=4)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical baseline creatinine',
                'verbose_name_plural': 'historical baseline creatinines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BaselineCreatinine',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lower_limit', models.DecimalField(decimal_places=2, default=Decimal('0.74'), max_digits=4)),
                ('units', models.CharField(choices=[('MGDL', 'mg/dL (milligrams per deciliter)')], default='MGDL', max_length=10, verbose_name='Units')),
                ('upper_limit', models.DecimalField(decimal_places=2, default=Decimal('1.35'), max_digits=4)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('patient', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('lower_limit', Decimal('0.74')), ('units', 'MGDL'), ('upper_limit', Decimal('1.35'))), name='baselinecreatinine_units_limits_valid')],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
