# Generated by Django 5.1.9 on 2025-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinecreatinine',
            name='units',
            field=models.CharField(choices=[('MGDL', 'mg/dL')], default='MGDL', max_length=10, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='historicalbaselinecreatinine',
            name='units',
            field=models.CharField(choices=[('MGDL', 'mg/dL')], default='MGDL', max_length=10, verbose_name='Units'),
        ),
    ]
