# Generated by Django 5.1.9 on 2025-07-10 14:05

import django.db.models.deletion
import django_extensions.db.fields
import rules.contrib.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGoutDetail',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('at_goal', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Is the patient at goal uric acid level? Goal is typically < 6.0 mg/dL.', null=True)),
                ('at_goal_long_term', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Has the patient been at goal uric acid six months or longer? Goal is typically < 6.0 mg/dL.')),
                ('flaring', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Any recent gout flares?', null=True)),
                ('on_ppx', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is the patient on flare prophylaxis therapy?', verbose_name='On PPx?')),
                ('on_ult', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is the patient on or starting ULT (urate-lowering therapy)?', verbose_name='On ULT?')),
                ('starting_ult', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is the patient starting ULT or is he or she still in the initial dose adjustment (titration) phase?', verbose_name='Starting Urate-Lowering Therapy (ULT)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical gout detail',
                'verbose_name_plural': 'historical gout details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GoutDetail',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('at_goal', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Is the patient at goal uric acid level? Goal is typically < 6.0 mg/dL.', null=True)),
                ('at_goal_long_term', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Has the patient been at goal uric acid six months or longer? Goal is typically < 6.0 mg/dL.')),
                ('flaring', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Any recent gout flares?', null=True)),
                ('on_ppx', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is the patient on flare prophylaxis therapy?', verbose_name='On PPx?')),
                ('on_ult', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is the patient on or starting ULT (urate-lowering therapy)?', verbose_name='On ULT?')),
                ('starting_ult', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is the patient starting ULT or is he or she still in the initial dose adjustment (titration) phase?', verbose_name='Starting Urate-Lowering Therapy (ULT)')),
                ('patient', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('at_goal', False), ('at_goal_long_term', False)), ('at_goal', True), models.Q(('at_goal__isnull', True), ('at_goal_long_term', False)), _connector='OR'), name='goutdetails_goutdetail_at_goal_valid')],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
