# Generated by Django 5.1.9 on 2025-07-12 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goutdetails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goutdetail',
            name='goutdetails_goutdetail_at_goal_valid',
        ),
        migrations.AddConstraint(
            model_name='goutdetail',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('at_goal', False), ('at_goal__isnull', False), ('at_goal_long_term', False)), ('at_goal', True),
                    models.Q(('at_goal__isnull', True), ('at_goal_long_term', False)),
                    _connector='OR'
                ),
                name='goutdetails_goutdetail_at_goal_valid',
            ),
        ),
    ]
