# Generated by Django 5.1.9 on 2025-07-13 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goutdetails', '0011_remove_goutdetail_goutdetails_goutdetail_at_goal_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goutdetail',
            name='goutdetails_goutdetail_at_goal_valid',
        ),
        migrations.AddConstraint(
            model_name='goutdetail',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('at_goal', False), ('at_goal_long_term', False)),
                    ('at_goal', True),
                    models.Q(('at_goal__isnull', True), ('at_goal_long_term', False)), _connector='OR'), name='goutdetail_at_goal_valid'),
        ),
    ]
