# Generated by Django 5.1.9 on 2025-09-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goutdetails', '0014_alter_goutdetail_patient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalGoutDetail',
        ),
    ]
