# Generated by Django 5.1.9 on 2025-05-28 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPseudopatientProfile',
            new_name='HistoricalPatientProfile',
        ),
        migrations.RemoveField(
            model_name='pseudopatientprofile',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='pseudopatientprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='historicalpatientprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical patient profile', 'verbose_name_plural': 'historical patient profiles'},
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pseudopatient_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='provider_alias',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='patientprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider__isnull', False), ('provider_alias__isnull', False)), models.Q(('provider__isnull', True), ('provider_alias__isnull', True)), _connector='OR'), name='patientprofile_alias_required_for_provider'),
        ),
        migrations.DeleteModel(
            name='PseudopatientProfile',
        ),
    ]
