# Generated by Django 5.1.9 on 2025-06-26 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_historicalpseudopatientprofile_historicalpatientprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientprofile',
            name='patientprofile_alias_required_for_provider',
        ),
        migrations.AlterField(
            model_name='historicalpatientprofile',
            name='provider_alias',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='provider_alias',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='patientprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider__isnull', False), ('provider_alias__isnull', False)), ('provider__isnull', True), _connector='OR'), name='patientprofile_alias_required_for_provider'),
        ),
    ]
