# Generated by Django 5.1.9 on 2025-10-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_patientprofile_patientprofile_alias_required_for_provider_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientprofile',
            name='patientprofile_alias_required_for_provider',
        ),
    ]
