# Generated by Django 5.1.9 on 2025-10-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_patientprofile_patientprofile_alias_required_for_provider'),
        ('users', '0005_historicaladmin_historicalpatient_historicalprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaladminprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalpatientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalproviderprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='admin',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaladminprofile',
            name='admin',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.admin'),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.patient'),
        ),
        migrations.AddField(
            model_name='historicalproviderprofile',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.provider'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='provider',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.provider'),
            preserve_default=False,
        ),
    ]
