# Generated by Django 5.1.9 on 2025-06-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaladmin_historicalpatient_historicalprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprovider',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalAdmin',
        ),
        migrations.DeleteModel(
            name='HistoricalPatient',
        ),
        migrations.DeleteModel(
            name='HistoricalProvider',
        ),
    ]
