# Generated by Django 5.1.9 on 2025-09-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_historicalpatient_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'get_latest_by': 'modified'},
        ),
    ]
